### ISSUE TITLE
Dirty working tree is ignored by the plugin

### ISSUE THREAD

**Issue by dglynch** [cinnober/semver-git#6]
If the user's working tree is dirty (that is, if there are any differences between the working tree and the `HEAD`) the plugin does not behave any differently. This can be a problem, because the resulting build artifacts will have a misleading version that does not reflect the actual code that was used to build them. In the extreme case, the abuse of `git reset --soft` can make it easy to build arbitrary code as any particular version (even a tagged version) without warning the user.

I propose to add support for the `--dirty` option of `git describe`. For example, if the version number for a particular commit would normally be `1.1.0-5.g5242341-SNAPSHOT`, then in the presence of a dirty working tree the version number would become something like `1.1.0-5.g5242341-dirty-SNAPSHOT` instead. The user would be able to configure this using something like:

```
// optionally: ext.dirtyMark = "-dirty" (default)
ext.snapshotSuffix = "<count>.g<sha><dirty>-SNAPSHOT"
```

The biggest question in my mind is this: do we consider the existing behaviour (that dirty work trees don't affect the output) to be a bug, or a feature? If it is a bug, then it should be fixed by changing the default behaviour of the plugin, even though this would technically be a breaking API change. If it is a feature, then the new "dirty" feature should be added in a way that does not affect existing users when they upgrade.

**Comment by mojocinn** [comment]
I think this is a good feature to add. Although I do not really view current functionality as a bug (it does what I would expect it to do) it is much too easy to make a mistake here. Adding it optionally as suggested would be a simple, yet effective solution to the problem.

**Comment by dglynch** [comment]
I'm still in the process of getting permission from my employer to sign the CLA, but I have pushed a proposed code change for anyone to review and comment on.

**Comment by emlun** [comment]
Awesome, thanks a lot! 😄😍
